--This is not finished!
--You will see where its not finished!

--Dutch
{
	permission_failure = "U hoeft geen moment toestemming om dit te doen.",
	disabled_whitelist = "De witte lijst voor deze job is uitgeschakeld.",
	no_whitelist_permission = "Je hebt geen toestemming om deze whitelist te bewerken.",
	search_jobs = "Zoeken jobs...",
	steamid_finder = "SteamID Finder",
	type = "Type",
	value = "Waarde",
	team_name = "Naam",
	select_job = "Selecteer een taak aan de linkerkant...",
	enable_whitelist = "Inschakelen Whitelist?",
	enabling_whitelist = "Inschakelen Whitelist...",
	add_to_whitelist = "Optellen bij Whitelist",
	disable_whitelist = "Uitschakelen Whitelist",
	clear_whitelist = "Clear Whitelist",
	search = "Zoeken...",
	no_data = "Geen gegevens!",
	retrieving = "Ophalen...",
	admin_mode = "Beheerder Mode",
	admin_tab = "Beheerder",
	jobs_tab = "Jobs",
	players_tab = "Spelers",
	default_team = "Dit is de standaard team. Je kunt niet whitelist de standaard team.",
	remove_from_whitelist = "Verwijderen uit Whitelist",
	player_name = "Naam",
	remove_from_whitelist_selected_tooltip = "Verwijder de geselecteerde gebruiker uit een whitelist",
	add_to_whitelist_selected_tooltip = "Voeg de geselecteerde gebruiker een whitelist",
	clear_whitelist_tooltip = "[Beheerder Alleen] Wist de whitelist. Alle SteamIDs en gebruikersgroepen worden verwijderd.",
	disable_whitelist_tooltip = "Schakelt de whitelist. Spelers kunnen vrij toetreden tot de baan.",
	add_to_whitelist_tooltip = "Voegt een SteamID, SteamID64 of gebruikersgroep aan de witte lijst voor deze job.",
  
  
  
  
  --NOT COMPLETED
	remove_from_whitelist_tooltip = "Removes the selected SteamID, SteamID64 or usergroup from the whitelist for this job.",
	in_jobs_file_tooltip = "You can't disable this whitelist because it is BWhitelist enabled in your DarkRP jobs file.",
	add_steamid = "Add SteamID/64",
	add_usergroup = "Add Usergroup",
	add_usergroup_modal = "Type the usergroup you want to add below.",
	add_steamid_modal = "Paste the SteamID/SteamID64 you want to add below.\nPlease remember that there is an easier way to do this, go to the \"Player\" tab in the menu!",
	error = "Error",
	not_a_steamid_or_64 = "That's not a SteamID or SteamID64!",
	already_exists = "That already exists in the whitelist!",
	doesnt_exist = "That doesn't exist in the whitelist!",
	copy = "Copy",
	copy_tooltip = "Copies the selected usergroup or SteamID.",
	player_left = "Sorry, it looks like that player's left the server.",
	no_enabled_whitelists = "There's no enabled whitelists that you have access to!",
	import_from_mayoz = "Import from Mayoz's Whitelisting System",
	import_from_nordahl = "Import from Nordahl's Whitelisting System",
	import_from_old_bwhitelist = "Import from old BWhitelist",
	view = "View",
	no_import = "It looks like we couldn't find the files/the files are corrupted that are required to import.",
	import_from_old_bwhitelist_tooltip = "If we can find any of the old BWhitelist files on your server, we'll convert them into the new files.",
	import_from_mayoz_tooltip = "If we can find any of Mayoz's Whitelisting System's files on your server, we'll convert them into BWhitelist files.",
	import_from_nordahl_tooltip = "If we can find any of Nordahl's Whitelisting System's files on your server, we'll convert them into BWhitelist files.",
	disable_all_whitelists = "All jobs will have their whitelists disabled. All data will stay.",
	enable_all_whitelists = "All jobs will have their whitelists enabled.",
	steamprofile = "Steam Profile",
	confirm = "Confirm",
	are_you_sure = "Are you sure you want to do this?",
	yes = "Yes",
	cancel = "Cancel",
	reset_everything = "Reset everything",
	reset_everything_tooltip = "WARNING: This will delete ALL whitelist data and enabled whitelists.",
	go = "Go",
	customcheck_team = "This team has a customCheck on it. This overrides BWhitelist.\n\nPlease change \"customCheck\" to \"BWhitelist_customCheck\"\nin your jobs file for your customCheck to work with BWhitelist.",
	removed_from_whitelist = "You were removed from the whitelist for \"%s\"",
	added_to_whitelist = "You were added to the whitelist for \"%s\"",
	disable_all_whitelists = "Disable all whitelists",
	enable_all_whitelists = "Enable all whitelists",
	player_left = "The player has left.",
	no_actions_available = "No actions available for this player.",
	remove_from_all_whitelists = "Remove from all whitelists",
	add_to_all_whitelists = "Add to all whitelists",
	clear_unknown_jobs = "Clear Unknown Jobs",
	clear_unknown_jobs_tooltip = "If there is whitelist data in the database related to a job that doesn't exist anymore, it will all be deleted with this button. The whitelist data of that job will be kept in case you need it in future.",
}
